music.play_tone(523, music.beat(BeatFraction.HALF))
music.rest(music.beat(BeatFraction.SIXTEENTH))
music.play_tone(523, music.beat(BeatFraction.WHOLE))
music.play_tone(349, music.beat(BeatFraction.HALF))
music.play_tone(523, music.beat(BeatFraction.WHOLE))
music.play_tone(587, music.beat(BeatFraction.WHOLE))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(587, music.beat(BeatFraction.HALF))
music.play_tone(523, music.beat(BeatFraction.WHOLE))
music.play_tone(349, music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.WHOLE))
music.play_tone(392, music.beat(BeatFraction.WHOLE))
music.rest(music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.HALF))
music.play_tone(349, music.beat(BeatFraction.WHOLE))
music.play_tone(330, music.beat(BeatFraction.HALF))
music.play_tone(659, music.beat(BeatFraction.WHOLE))
music.play_tone(523, music.beat(BeatFraction.HALF))
music.play_tone(523, music.beat(BeatFraction.HALF))
music.play_tone(440, music.beat(BeatFraction.HALF))
music.play_tone(523, music.beat(BeatFraction.WHOLE))
music.play_tone(587, music.beat(BeatFraction.HALF))
music.play_tone(392, music.beat(BeatFraction.WHOLE))
music.play_tone(440, music.beat(BeatFraction.WHOLE))
music.rest(music.beat(BeatFraction.WHOLE))
